config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :eletros
  resources :produtos
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/eletro.rb
class Eletro < ApplicationRecord
end

app/models/produto.rb
class Produto < ApplicationRecord
  has_one_attached :photo

  include PgSearch::Model
  pg_search_scope :search_product,
    against: [ :nome, :tipo ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/carne_controller.rb
class CarneController < ApplicationController

  def carne
  end
end

app/controllers/cozinha_controller.rb
class CozinhaController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :cozinha ]

  def cozinha
  end
end

app/controllers/eletros_controller.rb
class EletrosController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :index, :show , :new, :create]
  def index
    @eletros = Eletro.all
  end

  def show
    @eletro = Eletro.find(params[:id])
  end

  def new
    @eletro = Eletro.new
  end

  def create
    @eletro = Eletro.new(eletro_params)
    @eletro.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to eletro_path(@eletro)
  end

  private

  def eletro_params
    params.require(:eletro).permit(:nome, :valor)
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  skip_before_action :authenticate_user!, :only => [:index, :show, :new, :create, :destroy]
  def index
    if params[:query].present?
      @produtos = Produto.search_product(params[:query])
    else
      @produtos = Produto.all
    end
  end

  def show
    @produto=Produto.find(params[:id])
  end

  def new
    @produto = Produto.new
  end

  def create
    @produto = Produto.new(produto_params)
    @produto.save

    # no need for app/views/restaurants/create.html.erb
    redirect_to produto_path(@produto)
  end

  def destroy
    @produto = Produto.find(params[:id])
    @produto.destroy

    # no need for app/views/restaurants/destroy.html.erb
    redirect_to produtos_path
  end

  private

  def produto_params
    params.require(:produto).permit(:nome, :valor, :tipo, :photo)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/eletros/index.html.erb
<h1>Eletros abaixo</h1>
<%@eletros.each do |eletro|%>
  <h5><%= eletro.nome%></h5>
  <h5><%= eletro.valor%></h5>
  <img src="/assets/logo.PNG" alt="logo" id="logo">
<% end %>

app/views/eletros/new.html.erb
<%= form_for @eletro do |f| %>
  <%= f.label :nome %>
  <%= f.text_field :nome %>
  <%= f.label :valor %>
  <%= f.text_field :valor %>
  <%= f.submit %>
<% end %>

app/views/eletros/show.html.erb
<h1><%= @eletro.nome %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pontualmoveis</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="main">
  <div>
    <div class="d1"><div>
    <div class="d2"></div>
    <div class="d3"></div>
  </div>
</div>

<div class="flex">
  <%= link_to "Produtos", produtos_path %>
</div>

app/views/pages/rascunho_nav.html.erb
<div class="container-fluid px-0">
    <nav class="navbar navbar-expand-md navbar-light bg-white p-0"> <a class="navbar-brand mr-4" href="">
    <img src="/assets/logo.PNG" alt="logo" id="logo">
    <strong></strong></a>

    <button class="navbar-toggler mr-3" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span> </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item"> <a class="nav-link" href="#" id="navbarDropdown1" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Produtos<span class="fa fa-angle-down"></span></a>
                    <div class="dropdown-menu" id="dropdown-menu1" aria-labelledby="navbarDropdown1">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-shopping-cart"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0"><a href="cozinha">EletroCozinha</a></h6> <small class="text-muted">Cozinhar ficou mais legal</small>
                                            </a> </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-gavel"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">EletroFerramentas</h6> <small class="text-muted">Para sua obra!</small>
                                            </a> </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row d-flex tab">

                                    </div>
                                </div>
                                <div class="col-md-6">

                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-briefcase"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">Eletromóveis</h6> <small class="text-muted">Para sua casa</small>
                                            </a> </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-bolt"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">Eletrokids</h6> <small class="text-muted">Para a criançada</small>
                                            </a> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item"> <a class="nav-link" href="#" id="navbarDropdown2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Carnê<span class="fa fa-angle-down"></span></a>
                    <div class="dropdown-menu" id="dropdown-menu2" aria-labelledby="navbarDropdown2">
                        <div class="container">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-folder"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0"><a href="carne">Ação1</a></h6>
                                            </a> </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-question"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">Ação2</h6>
                                            </a> </div>
                                    </div>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-calculator"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">Ação3</h6>
                                            </a> </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-paper-plane"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">Ação4</h6> <small class="text-muted">Experiences</small>
                                            </a> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li class="nav-item"> <a class="nav-link" href="#" id="navbarDropdown3" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Lojas<span class="fa fa-angle-down"></span></a>
                    <div class="dropdown-menu" id="dropdown-menu3" aria-labelledby="navbarDropdown3">
                        <div class="container">
                            <div class="row">
                                <div class="col-lg-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-feed"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">Capela do Alto</h6> <small class="text-muted">legenda</small>
                                            </a> </div>
                                    </div>
                                </div>
                                <div class="col-lg-6">
                                    <div class="row d-flex tab">
                                        <div class="fa-icon text-center"> <span class="fa fa-question"></span> </div>
                                        <div class="d-flex flex-column"> <a class="dropdown-item" href="#">
                                                <h6 class="mb-0">Araçoiaba da Serra</h6> <small class="text-muted">legenda</small>
                                            </a> </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </nav>
</div>

app/views/produtos/index.html.erb
<div class="lista">
  <h1>Lista de produtos</h1>
</div>

<div class="lista">
  <%= form_tag produtos_path, method: :get do %>
    <%= text_field_tag :query,
      params[:query],
      class: "form-control",
      placeholder: "Find a product"
    %>
    <%= submit_tag "Search", class: "btn btn-primary" %>
  <% end %>
</div>

<div class="lista">
  <% @produtos.each do |produto| %>
      <div class="card-product">
          <% if produto.photo.attached? %>
            <%= cl_image_tag produto.photo.key, crop: :fill,class:"img_preview" %>
          <% else%>
            <h1></h1>
          <%end%>
        <div class="card-product-infos">
          <h2><%= produto.nome %></h2>
          <p>Descrição:<%= produto.tipo %></p>
          <p>R$<%= produto.valor %></p>
        </div>
        <a href="https://api.whatsapp.com/send?phone=+551599804-2088"  style="color:white">Comprar</a>
      </div>
  <% end %>
</div>
<div class="btn">
  <%= link_to "Criar produto",  new_produto_path %>
</div>

app/views/produtos/new.html.erb
<div class="form">
              <%= simple_form_for @produto do |f| %>

                <h1><%=f.input :nome,
                            required: true,
                            autofocus: true,
                            class: 'form-style border border-1 border-white rounded',
                            placeholder: "Nome" %>
                <i class='input-icon uil uil-at'></i></h1>


                <h1><%=f.input :tipo,
                            required: false,
                            autofocus: true,
                            class: 'form-style border border-1 border-white rounded',
                            placeholder: "Tipo" %>
                <i class='input-icon uil uil-at'></i></h1>

                <h1><%=f.input :valor,
                            required: true,
                            autofocus: true,
                            min: '1',
                            class: 'form-style border border-1 border-white rounded',
                            placeholder: "Valor" %>
                <i class='input-icon uil uil-at'></i></h1>


                <h1><%= f.input :photo,
                            as: :file,
                            class: 'btn-sign mb-1 mt-3 rounded-3' %></h1>

                <h1><%= f.submit "Criar produto", class: 'submit' %></h1>

              <% end %>
</div>

app/views/produtos/show.html.erb
<div class="central">
  <div class="card-produto">
    <%= cl_image_tag @produto.photo.key, class:"card-product img", height: 300, width: 413, crop: :fill %>
      <div class="card-product-infos">
        <div>
          <h2><%= @produto.nome %></h2>
            <p><%= @produto.tipo %><p>
        </div>
           <h2>R$<%= @produto.valor %></h2>
        <img src="https://scontent.fcgh40-1.fna.fbcdn.net/v/t39.30808-6/246362410_4201804193263590_3014684204083413757_n.jpg?_nc_cat=107&ccb=1-5&_nc_sid=09cbfe&_nc_eui2=AeF6xMP0GwoTMRr4d4BvzHxkDb5A_ZAKBe4NvkD9kAoF7n5MGhpwsEe2rVK0DSwnTDQ&_nc_ohc=enN22lQwIv8AX9cUHM6&_nc_zt=23&_nc_ht=scontent.fcgh40-1.fna&oh=b53814d2d068a76b3f3be810c0acd545&oe=619BE8B7" class="card-trip-user avatar-bordered" alt="">
      </div>
      <%= link_to "Deletar ",
                  produto_path(@produto),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %>
      <div class="btn">
        <button style="color:white"><%= link_to "Aprovar e ver lista",  produtos_path %></button>
       </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>